[languages]
names=["python", "node"]

[phases.setup]

[phases.build]
commands = ["npm run build"]

[start]
command = "cd jarvis-backend-fixed && gunicorn --bind 0.0.0.0:5000 --workers 2 --timeout 30 wsgi:application"