[build]
builder = "nixpacks"

[deploy]
startCommand = "cd jarvis-backend && gunicorn --bind 0.0.0.0:$PORT --workers 2 wsgi:application"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { FLASK_ENV = "production" }

