[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c \"gunicorn --bind 0.0.0.0:${PORT:-5000} --workers 2 --timeout 30 wsgi:application\""
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[environments.production]
variables = { FLASK_ENV = "production", PYTHONPATH = "/app/src" }

